language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
# command to install dependencies
install:
 # - pip install pipreqs
 # - pipreqs \Users\Tob14\Dropbox\Elektronikingeniør\3.semester\E3SWE\SWE2017
  
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  
  